### ISSUE TITLE
Can't use SpeechRecognition on firefox

### ISSUE THREAD

**Issue by WeiChun0911** [turnoffthelights/Turn-Off-the-Lights-Firefox-extension-WebExtensions#1]
Is this feature Chrome only?
webkitSpeechRecognition() is not defined on firefox

**Comment by turnoffthelights** [comment]
Thank you to report this! Firefox is still not ready for the Speech Recognition feature. However, you can use it on Chromium web browsers such as Google Chrome, Opera, and Yandex.
Please for further questions use the support form: [https://www.turnoffthelights.com/support](https://www.turnoffthelights.com/support)
We are happy to help you over there.

Thanks,
