### ISSUE TITLE
Can't disable keyboard shortcut Ctrl+Shift+L

### ISSUE THREAD

**Issue by laurens94** [turnoffthelights/Turn-Off-the-Lights-Firefox-extension-WebExtensions#2]
I've disabled the option "Enable the keyboard shortcuts below", yet the keyboard shortcut Ctrl + Shift + L is still active.

This is a problem because I use that same shortcut to auto-fill my Bitwarden passwords.

Is there a way to disable the hotkey entirely?
Thanks!

**Comment by turnoffthelights** [comment]
In the Firefox web browser you can customize the shortcut in the addons preference page -> shortcut.
1. Open the Firefox web browser
2. And go to this page:
about:addons
3. Click on the wrench icon, and in the menu choose the item "Manage Extension Shortcuts"
4. Scroll down until you see the "Turn Off the Lights" topic. And here you can edit and remove (=using the trash icon) the shortcuts of the Turn Off the Lights Firefox extension.

Please for questions or help, use next time the support form at https://www.turnoffthelights.com/support

Thanks
