### ISSUE TITLE
Permissions for all tabs/websites

### ISSUE THREAD

**Issue by Andrade** [turnoffthelights/Turn-Off-the-Lights-Firefox-extension-WebExtensions#3]
Is there a reason why the extension needs access to all website data?

> Access browser tabs
> Access your data for all websites

Couldn't this be restricted for only the necessary domains? (youtube, vimeo, etc)

**Comment by turnoffthelights** [comment]
Hi there,

The Turn Off the Lights browser extension works on all websites, and that even on websites that with no video player on the web page. So users can dim the web page on his favorite website and make it a better and comfortable read experience.
However, you can restrict the extension (on Chromium web browsers) that it only works on YouTube (or Vimeo, etc). For example, when you click right on the gray lamp button, you can choose to restrict it to that open website. And prevent to load the Turn Off the Lights browser extension on other websites. If you want to use it on that new website, just a single click on the gray lamp button. And it will activate it on that website.
<img width="878" alt="Screen Shot 2020-11-12 at 11 25 24" src="https://user-images.githubusercontent.com/9094100/98928411-0af17980-24da-11eb-8e7b-ddddf0b01896.png">
And if you want to work the automatically dim the webpage on a certain website, you can enable in the Turn Off the Lights Options page the whitelist/blacklist radio button.

Please for non-developer questions use the support contact form at https://www.turnoffthelights.com/support
At the bottom of the web page, you see the option to contact by live chat or email. We are happy to help you over there.

Thanks,
